# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.08.134136'

RELEASE_GIT_HEAD = '0039a08cce6a1bdda12587767a7f4c009ee17bd7'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Sakura-Byte/yt-dlp'

ORIGIN = 'Sakura-Byte/yt-dlp'

_pkg_version = '2026.03.08.134136'
