# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.20.055151'

RELEASE_GIT_HEAD = '92a8c21dbdbf4e74b45287c4737481135e298e37'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Sakura-Byte/yt-dlp'

ORIGIN = 'Sakura-Byte/yt-dlp'

_pkg_version = '2026.03.20.055151'
