# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.08.131322'

RELEASE_GIT_HEAD = '3c6ff45396785738244b03eb8740aa751f619aab'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Sakura-Byte/yt-dlp'

ORIGIN = 'Sakura-Byte/yt-dlp'

_pkg_version = '2026.03.08.131322'
